### ISSUE TITLE
Solution for clearing notification queue when switching view controllers

### ISSUE THREAD

**Issue by boscojwho** [ajerez/AJNotificationView#11]
I found that when you segue from one view controller to another, and have any unfinished notifications, it takes a while for new notifications to appear in the new view controller.  Using the -hide method didn't resolve this issue.

So, I added a class method which you can use to manually clear global notification queue when you switch between view controllers.  This made all my notifications appear at the right times on iOS 6.

(Class Method) (AJNotificationView *)clearNotificationQueue {
    notificationQueue = nil;

```
return nil;
```

}

**Comment by ehuynh** [comment]
Yes, this issue is bugging me too. @ajerez can you include a fix in the next release? Even something as simple as @boscojwho fix would be helpful.

**Comment by ajerez** [comment]
Thanks, I'm sorry but lately I don't have much time for working in my repos.

**Comment by ehuynh** [comment]
No Worries. Can you tag the commit with a new version? I'm using AJNotificationView through Cocoapods. I can create an updated podspec in the Specs repo.

**Comment by ajerez** [comment]
Done.
I'm updated de Cocoapods Speccs repo too ;)

**Comment by ehuynh** [comment]
sweet. Thank again
