### ISSUE TITLE
Rounded corners in the top of the notification

### ISSUE THREAD

**Issue by troelsrichter** [ajerez/AJNotificationView#12]
Are you rounding the corners at the top? it doesn't look right because the view is attached to the top.
![iOS Simulator Screen shot Dec 24 2012 2 06 35 PM](https://f.cloud.github.com/assets/905181/29803/cda73ffe-4dca-11e2-95e0-221e1230bd2d.png)

**Comment by ajerez** [comment]
In iPad, iOS forces the rounded corners in the main window, my library don't draw rounded corners.
You can avoid this hiding your status bar.

http://stackoverflow.com/questions/5518977/how-does-one-eliminate-the-rounded-corners-on-the-main-window-on-an-ipad-app
