### ISSUE TITLE
Detail disclosure is on top of the text when the text length is long.

### ISSUE THREAD

**Issue by coder007** [ajerez/AJNotificationView#9]
Currently the text does not take into account of the region occupied by the detail disclosure when it is shown. To see the issue, either reproduce it as follow or see the image attached below.

For example, using the sample demo project. Change the default text from "Detail disclosure notification" to "Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. ", like so:

``` objc
- (IBAction)showOrangeNotificationWithoutlines:(id)sender {
    [AJNotificationView showNoticeInView:self.view
                                    type:AJNotificationTypeBlue
                                   title:@"Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet. "
                         linedBackground:AJLinedBackgroundTypeAnimated
                               hideAfter:2.5f offset:0.0f delay:0.0f detailDisclosure:YES
                                response:^{
                                    NSLog(@"Response block");
                                }
     ];
}
```

![iOS Simulator Screen shot 14 12 2012 4 13 21 PM](https://f.cloud.github.com/assets/1185589/12664/47a3738e-45ad-11e2-9bda-af89ee0f720b.png)

**Comment by ajerez** [comment]
I'll try to fix this today, thanks

**Comment by ajerez** [comment]
Fixed
